name: CactusRush
version: '${project.version}'
main: com.github.firewolf8385.cactusrush.CactusRush
api-version: 1.18
authors: [ firewolf8385, dzah ]
description: Intense Desert Minigame Designed by dzah
depend: [PlaceholderAPI, JadedCore]

commands:
  admin:
    description: Game admin command
  arena:
    description: Runs the arena command.
  cactusrush:
    description: Displays information about CactusRush.
    aliases: [cr]
  play:
    description: Runs the play command
  mode:
    description: Admin mode command.