name: CactusRush
version: '${project.version}'
main: net.jadedmc.cactusrush.CactusRushPlugin
api-version: "1.19"
author: JadedMC
description: Intense Desert Minigame
depend: [PlaceholderAPI, JadedCore, JadedChat]

commands:
  admin:
    description: Game admin command
  arena:
    description: Runs the arena command.
  arenas:
    description: View all loaded arenas.
  cactusrush:
    description: Displays information about CactusRush.
    aliases: [cr]
  play:
    description: Runs the play command
  modes:
    description: View the modes menu.
  spectate:
    description: Spectate a game
    aliases: [spec,watch,view]